### ISSUE TITLE
Backup is not working for App Image on Fedora.

### ISSUE THREAD

**Issue by uncharted-user** [internxt/drive-desktop-linux#23]
I am using App Image v 2.4.0 and Fedora Linux 40 (Workstation Edition). Clicking on the backup now after selecting the folder automatically stops backup after 2–3 seconds, then if I click 3–4 times then it got hang every time.

**Comment by RasheedAZ** [comment]
Same with deb package.

**Comment by fvsegarra** [comment]
We're investigating this issue, please kindly send us the app log files alongside the link to this issue to [hello@internxt.com](mailto:hello@internxt.com)
Thank you
